### ISSUE TITLE
TypeError: list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by momtarks** [bogomhd/BeoLightControl#1]
Am very new to this however seem to be getting the above when adding the B&O product. Any ideas?

Traceback (most recent call last):
  File "/home/pi/BeoLightControl/BeoLightControl.py", line 421, in <module>
    beoLightControl.start()
  File "/home/pi/BeoLightControl/BeoLightControl.py", line 350, in start
    self.select_beo_product()                
  File "/home/pi/BeoLightControl/BeoLightControl.py", line 250, in select_beo_product
    config[config_product] = {config_product_name: self.beo_device_name, config_ip: self.beo_device_ip}
TypeError: list indices must be integers or slices, not str

**Comment by bogomhd** [comment]
Hi, I'll try to see if I can add some more information to the code. Then we can figure out whats wrong. I'll get back to you.

**Comment by bogomhd** [comment]
May I ask what product you are using?

**Comment by momtarks** [comment]
> May I ask what product you are using?

I’m using the stage if that is of any help!

**Comment by bogomhd** [comment]
I see the error now. I'll see if I can find a solution.

**Comment by bogomhd** [comment]
So it should be fixed now. You need to do the following:

1. Delete the BeoLightControl.yaml file.
2. Do a "git pull"
3. Do the initial configuration again. (sorry! :( )

Hope it helps! otherwise let me know.

**Comment by momtarks** [comment]
All Working 👍 

Thanks you all your help :)
