### ISSUE TITLE
run as a service

### ISSUE THREAD

**Issue by cubaneight** [bogomhd/BeoLightControl#2]
Hi! Great Script, works well in my setup with a Besound Core and Hue Bridge.

Since I am not a coder - could you add the possibility to store the selected Light /Group in the yaml file and a solution to start the listener immediately when the script runs? Then, I could start it as a service, and not from the command line.

Thanks a lot!"

BR
Dieter

**Comment by bogomhd** [comment]
Hi Dieter.

It is the plan to store the selected light/group. I just haven't gotten to it yet. Good idea with the listner auto start. I'll see if what I can do.

BR
Michael

**Comment by cubaneight** [comment]
Perfect, thanks!

BR
Dieter


—
Dr. Dieter Kohl
+43 664 3824391<tel:+43%20664%203824391>
dieter.kohl@aon.at<mailto:dieter.kohl@aon.at>
EAA 1028610<tel:1028610>

Am 10.01.2021 um 17:21 schrieb Michael Jakobsen Højgaard <notifications@github.com>:

﻿

Hi Dieter.

It is the plan to store the selected light/group. I just haven't gotten to it yet. Good idea with the listner auto start. I'll see if what I can do.

BR
Michael

**Comment by bogomhd** [comment]
Well the first thing is done... If you do a pull from github it should store the selected light/group in the yaml file the next time you select one. Let me know if you encounter any problems.

The auto start is for another day. :)

**Comment by cubaneight** [comment]
Good job!

Works well here with BS Core, I‘ll for sure buy you a coffee once the autostart of the listener is working! 👍

BR
Dieter



Am 11.01.2021 um 22:12 schrieb Michael Jakobsen Højgaard <notifications@github.com>:

﻿

Well the first thing is done... If you do a pull from github it should store the selected light/group in the yaml file the next time you select one. Let me know if you encounter any problems.

The auto start is for another day. :)

**Comment by bogomhd** [comment]
So I finally got to it... I made it possible to launch the listner directly by using the option "-l".

Like:
`./BeoLightControl.py -l`

Let me know if it works out!

**Comment by cubaneight** [comment]
Great stuff – works flawlessly!

Thanks for sharing your work and let me know how to buy you a coffee 😉

BR,
Dieter


Von: Michael Jakobsen Højgaard <notifications@github.com>
Antworten an: bogomhd/BeoLightControl <reply@reply.github.com>
Datum: Donnerstag, 21. Jänner 2021 um 20:55
An: bogomhd/BeoLightControl <BeoLightControl@noreply.github.com>
Cc: Dieter Kohl <dieter@sierrakilo.at>, Author <author@noreply.github.com>
Betreff: Re: [bogomhd/BeoLightControl] run as a service (#2)


So I finally go to it... I made it possible to launch the listner directly by using the option "-l".

Like:
./BeoLightControl.py -l

Let me know if it works out!

**Comment by bogomhd** [comment]
Great that it worked! Raincheck on the coffee! ;)
