### ISSUE TITLE
How can you run it constantly?

### ISSUE THREAD

**Issue by Almansio** [bogomhd/BeoLightControl#3]

**Comment by bogomhd** [comment]
Hi @Almansio. I'll try and see if I can update the guide soon to cover this case. Thanks for reaching out. :+1:

**Comment by bogomhd** [comment]
@Almansio Sorry for the late reply. I had some problems with updating my Pi. Anyways. I think what you are looking for is to run BeoLightControl as a service.
Here you can see how: https://gist.github.com/emxsys/a507f3cad928e66f6410e7ac28e2990f

I tried it my self and created a service file called lightcontrol.service with the following content:
```
[Unit]
Description=BeoLightControl
After=multi-user.target

[Service]
Type=simple
WorkingDirectory=/home/pi/BeoLightControl
ExecStart=/usr/bin/python3 /home/pi/BeoLightControl/BeoLightControl.py -l
Restart=on-abort

[Install]
WantedBy=multi-user.target
```
Please remember to change the paths to where you downloaded BeoLightControl.

With this BeoLightControl will be loaded on every boot. Do remeber to stop the service and run the script manually if you want to change settings.

Hope it makes sense? otherwise let me know.

**Comment by Almansio** [comment]
Hi Michael

I followed the steps and changed the paths to mine. Unfortunately i'm getting the following failure when executing the sudo systemctl status command. Below the complete description of the failure. Hope you can help me out :)

pi@homebridge:~/BeoLightControl $ sudo systemctl status lightcontrol.service
● lightcontrol.service - BeoLightControl
     Loaded: loaded (/lib/systemd/system/lightcontrol.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Tue 2022-05-17 19:07:27 CEST; 20s ago
    Process: 18047 ExecStart=/usr/bin/python /home/pi/BeoLightControl/BeoLightControl.py -1 (code=exited, status=1/FAILURE)
   Main PID: 18047 (code=exited, status=1/FAILURE)
        CPU: 518ms

May 17 19:07:27 homebridge python[18047]: Traceback (most recent call last):
May 17 19:07:27 homebridge python[18047]:   File "/home/pi/BeoLightControl/BeoLightControl.py", line 474, in <module>
May 17 19:07:27 homebridge python[18047]:     beoLightControl.start(listner_mode)
May 17 19:07:27 homebridge python[18047]:   File "/home/pi/BeoLightControl/BeoLightControl.py", line 428, in start
May 17 19:07:27 homebridge python[18047]:     self.ui()
May 17 19:07:27 homebridge python[18047]:   File "/home/pi/BeoLightControl/BeoLightControl.py", line 374, in ui
May 17 19:07:27 homebridge python[18047]:     val = input("\nWhat do you want to do?\n1: Select product\n2: Select Light or Group\n3: Start/Stop listner\n4: Quit\n")
May 17 19:07:27 homebridge python[18047]: EOFError: EOF when reading a line
May 17 19:07:27 homebridge systemd[1]: lightcontrol.service: Main process exited, code=exited, status=1/FAILURE
May 17 19:07:27 homebridge systemd[1]: lightcontrol.service: Failed with result 'exit-code'.

**Comment by Almansio** [comment]
> 

Works like a charm!!!!! Many thanks!

**Comment by Almansio** [comment]
Hi Micheal,

Don’t be sorry at all! Much appreciated for your input! I’m gone for a few days but when I’m back I will give at a try.

And again thank you for your thoughts!👊🏽



Op 25 apr. 2022 om 19:43 heeft Michael Jakobsen Højgaard ***@***.***> het volgende geschreven:

﻿
@Almansio Sorry for the late reply. I had some problems with updating my Pi. Anyways. I think what you are looking for is to run BeoLightControl as a service.
Here you can see how: https://gist.github.com/emxsys/a507f3cad928e66f6410e7ac28e2990f

I tried it my self and created a service file called lightcontrol.service with the following content:

[Unit]
Description=BeoLightControl
After=multi-user.target

[Service]
Type=simple
WorkingDirectory=/home/pi/BeoLightControl
ExecStart=/usr/bin/python3 /home/pi/BeoLightControl/BeoLightControl.py -l
Restart=on-abort

[Install]
WantedBy=multi-user.target
Please remember to change the paths to where you downloaded BeoLightControl.

With this BeoLightControl will be loaded on every boot. Do remeber to stop the service and run the script manually if you want to change settings.

Hope it makes sense? otherwise let me know.

**Comment by Almansio** [comment]
Hero! 😉

Op 20 apr. 2022 om 07:50 heeft Michael Jakobsen Højgaard ***@***.***> het volgende geschreven:

﻿
Hi @Almansio. I'll try and see if I can update the guide soon to cover this case. Thanks for reaching out. 👍
